version: "3"
services:
  ros2_micro_vscode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HUSARNET_JOIN_CODE=YOUR_JOIN_CODE
      - HUSARNET_DEVICE_NAME=YOUR_DEVICE_NAME
